/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controls.Tools;
import DB.ConectionDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmed
 */
public class Categories extends javax.swing.JFrame {

    /**
     * Creates new form Categories
     */
    public Categories() {
        initComponents();
        delete.setEnabled(false);
        save.setVisible(false);
        save.setEnabled(false);
        jTcat.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        barcode = new javax.swing.JTextField();
        jmeasuring = new javax.swing.JComboBox<>();
        priceBill = new javax.swing.JTextField();
        priceSale = new javax.swing.JTextField();
        count = new javax.swing.JTextField();
        jDateExpierd = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        save = new javax.swing.JButton();
        newCat = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTcat = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        backgraund = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("رقم التسلسل :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1190, 70, 120, 19);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("رقم البار كود :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(780, 80, 140, 19);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("اسم الصنف :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1190, 190, 90, 19);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("سعر الشراء :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1190, 240, 90, 19);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("سعر البيع :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1190, 290, 90, 19);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText(" انتهاء الصلاحية :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(780, 130, 120, 19);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("وحدة القياس :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(780, 180, 140, 19);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("العدد او الكمية :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(780, 240, 140, 19);

        id.setEditable(false);
        id.setBackground(new java.awt.Color(204, 204, 204));
        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id.setForeground(new java.awt.Color(177, 1, 1));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 1, 1)));
        getContentPane().add(id);
        id.setBounds(980, 70, 199, 30);

        barcode.setBackground(new java.awt.Color(204, 204, 204));
        barcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        barcode.setForeground(new java.awt.Color(177, 1, 1));
        barcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 1, 1)));
        getContentPane().add(barcode);
        barcode.setBounds(570, 70, 199, 30);

        jCategory.setBackground(new java.awt.Color(204, 204, 204));
        jCategory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCategory.setForeground(new java.awt.Color(177, 1, 1));
        jCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 1, 1)));
        getContentPane().add(jCategory);
        jCategory.setBounds(980, 180, 199, 30);

        jsection.setBackground(new java.awt.Color(204, 204, 204));
        jsection.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jsection.setForeground(new java.awt.Color(177, 1, 1));
        jsection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jsection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 1, 1)));
        getContentPane().add(jsection);
        jsection.setBounds(980, 130, 199, 30);

        jmeasuring.setBackground(new java.awt.Color(204, 204, 204));
        jmeasuring.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jmeasuring.setForeground(new java.awt.Color(177, 1, 1));
        jmeasuring.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "كيلو جرام", "جرام", "علبة", "كيس", "متر", "زجاجه" }));
        jmeasuring.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 1, 1)));
        getContentPane().add(jmeasuring);
        jmeasuring.setBounds(570, 170, 199, 30);

        priceBill.setBackground(new java.awt.Color(204, 204, 204));
        priceBill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        priceBill.setForeground(new java.awt.Color(177, 1, 1));
        priceBill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        priceBill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 1, 1)));
        getContentPane().add(priceBill);
        priceBill.setBounds(980, 230, 199, 30);

        priceSale.setBackground(new java.awt.Color(204, 204, 204));
        priceSale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        priceSale.setForeground(new java.awt.Color(177, 1, 1));
        priceSale.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        priceSale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 1, 1)));
        getContentPane().add(priceSale);
        priceSale.setBounds(980, 280, 199, 30);

        count.setBackground(new java.awt.Color(204, 204, 204));
        count.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        count.setForeground(new java.awt.Color(177, 1, 1));
        count.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        count.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(177, 1, 1)));
        getContentPane().add(count);
        count.setBounds(570, 230, 199, 30);

        jDateExpierd.setBackground(new java.awt.Color(177, 1, 1));
        jDateExpierd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDateExpierd.setForeground(new java.awt.Color(177, 1, 1));
        jDateExpierd.setDateFormatString("yyyy-MM-dd");
        jDateExpierd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jDateExpierd);
        jDateExpierd.setBounds(570, 120, 199, 30);

        jButton1.setBackground(new java.awt.Color(177, 1, 1));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("+");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(920, 180, 50, 30);

        delete.setBackground(new java.awt.Color(177, 1, 1));
        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(204, 204, 204));
        delete.setText("حذف الصنف المحدد");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(126, 130, 270, 50);

        update.setBackground(new java.awt.Color(177, 1, 1));
        update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update.setForeground(new java.awt.Color(204, 204, 204));
        update.setText("تحديث");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(126, 190, 270, 50);

        save.setBackground(new java.awt.Color(177, 1, 1));
        save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save.setForeground(new java.awt.Color(204, 204, 204));
        save.setText("حفظ");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(126, 190, 270, 50);

        newCat.setBackground(new java.awt.Color(177, 1, 1));
        newCat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        newCat.setForeground(new java.awt.Color(204, 204, 204));
        newCat.setText("إضافة صنف جديد");
        newCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCatActionPerformed(evt);
            }
        });
        getContentPane().add(newCat);
        newCat.setBounds(126, 278, 270, 50);

        home.setBackground(new java.awt.Color(177, 1, 1));
        home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(204, 204, 204));
        home.setText("الصفحة الرئيسية");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(126, 360, 270, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("ملاحظات :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(780, 280, 140, 19);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("بحث :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1260, 410, 73, 22);

        Search.setBackground(new java.awt.Color(204, 204, 204));
        Search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Search.setForeground(new java.awt.Color(177, 1, 1));
        Search.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(177, 1, 1), 1, true));
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SearchKeyTyped(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(573, 410, 680, 30);

        jTcat.setBackground(new java.awt.Color(177, 1, 1));
        jTcat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTcat.setForeground(new java.awt.Color(204, 204, 204));
        jTcat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ملاحظات", "العدد او الكمية", "وحدة القياس", "تاريخ انتهاء الصلاحية", "سعر البيع", "سعر الشراء", "اسم الصنف", "القسم", "الباركود", "الرقم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTcat.setGridColor(new java.awt.Color(255, 255, 255));
        jTcat.setOpaque(false);
        jTcat.setSelectionForeground(new java.awt.Color(177, 1, 1));
        jTcat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTcatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTcat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(9, 452, 1350, 230);

        jButton4.setBackground(new java.awt.Color(177, 1, 1));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("+");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(920, 130, 50, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("اسم القسم :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1190, 130, 90, 19);

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));

        notes.setBackground(new java.awt.Color(204, 204, 204));
        notes.setColumns(20);
        notes.setRows(5);
        jScrollPane2.setViewportView(notes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(570, 276, 200, 90);

        backgraund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1624847.jpg"))); // NOI18N
        getContentPane().add(backgraund);
        backgraund.setBounds(0, 0, 1366, 705);

        setSize(new java.awt.Dimension(1385, 744));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Section_Name s = new Section_Name();
        s.setDefaultCloseOperation(2);
        s.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Category_Name c = new Category_Name();
        c.setDefaultCloseOperation(2);
        c.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void lestCategories() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ملاحظات");
        table.addColumn("العدد او الكمية");
        table.addColumn("وحدة القياس");
        table.addColumn("انتهاء الصلاحية");
        table.addColumn("سعر الشراء");
        table.addColumn("سعر البيع");
        table.addColumn("اسم الصنف");
        table.addColumn("القسم");
        table.addColumn("الباركود");
        table.addColumn("الرقم");

        try {
            Connection con = ConectionDB.setcon();
            String sqls = "select * from categories";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sqls);

            while (rs.next()) {
                table.addRow(new Object[]{
                    rs.getString(10),
                    rs.getString(9),
                    rs.getString(8),
                    rs.getString(7),
                    rs.getString(6),
                    rs.getString(5),
                    rs.getString(4),
                    rs.getString(3),
                    rs.getString(2),
                    rs.getString(1),});
                jTcat.setModel(table);

            }
        } catch (Exception ex) {

        }
    }
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if ("".equals(id.getText()) || "".equals(jCategory.getSelectedItem()) || "".equals(jsection.getSelectedItem()) || "".equals(priceSale.getText()) || "".equals(jmeasuring.getSelectedItem()) || "".equals(count.getText())) {
            JOptionPane.showMessageDialog(this, "يجب ملئ البيانات", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            int co = JOptionPane.showConfirmDialog(this, "هل تريد حفظ البيانات", "تأكيد", JOptionPane.WARNING_MESSAGE);
            if (co == JOptionPane.YES_OPTION) {
                SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
                String exDate = f.format(jDateExpierd.getDate());
                String add = "INSERT INTO CATEGORIES VALUES(" + id.getText() + ", '" + barcode.getText() + "','" + jsection.getSelectedItem() + "','" + jCategory.getSelectedItem() + "','" + priceSale.getText() + "','"
                        + priceBill.getText() + "','" + exDate + "','" + jmeasuring.getSelectedItem() + "','" + count.getText() + "','" + notes.getText() + "')";
                boolean ifS = DB.GoDB.runNunQuery(add);
                if (ifS) {
                    JOptionPane.showMessageDialog(this, "تم حفظ البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                    lestCategories();
                    Tools.clearText(this);
                    jCategory.setSelectedItem(null);
                    jsection.setSelectedItem(null);
                    update.setEnabled(false);
                    update.setVisible(true);
                    save.setVisible(false);
                    save.setEnabled(false);

                } else {
                    JOptionPane.showMessageDialog(this, "لم يتم الحفظ", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void newCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCatActionPerformed
        Tools.clearText(this);
        jCategory.setSelectedItem(null);
        jsection.setSelectedItem(null);
        update.setEnabled(false);
        update.setVisible(false);
        save.setVisible(true);
        save.setEnabled(true);
        delete.setVisible(false);
        delete.setEnabled(false);
        id.setText(DB.GoDB.autoNumber("Categories", "Number"));
        barcode.requestFocus();
    }//GEN-LAST:event_newCatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GoDB.icon(this);
        DB.GoDB.fillCompo("category", "Category", jCategory);
        DB.GoDB.fillCompo("sections", "Section", jsection);
        jCategory.setSelectedItem(null);
        jsection.setSelectedItem(null);
        update.setEnabled(false);
        lestCategories();
    }//GEN-LAST:event_formWindowOpened


    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if ("".equals(id.getText()) || "".equals(jCategory.getSelectedItem()) || "".equals(jsection.getSelectedItem()) || "".equals(priceSale.getText()) || "".equals(jmeasuring.getSelectedItem()) || "".equals(count.getText())) {
            JOptionPane.showMessageDialog(this, "يجب ملئ البيانات", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            int co = JOptionPane.showConfirmDialog(this, "هل تريد تحديث البيانات", "تأكيد", JOptionPane.WARNING_MESSAGE);
            if (co == JOptionPane.YES_OPTION) {
                SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
                String exDate = f.format(jDateExpierd.getDate());
                String add = "UPDATE CATEGORIES SET Section='" + jsection.getSelectedItem() + "', Category='" + jCategory.getSelectedItem() + "', Price_Buy='" + priceBill.getText() + "', Price_Sale='" + priceSale.getText()
                        + "', Barcode='" + barcode.getText() + "', Expierd_Date='" + exDate + "', Measuring='" + jmeasuring.getSelectedItem() + "', Count='" + count.getText() + "', Notes='" + notes.getText() + "' WHERE Number=" + id.getText();
                boolean ifU = DB.GoDB.runNunQuery(add);
                if (ifU) {
                    JOptionPane.showMessageDialog(this, "تم تحديث البيانات", "نجح", JOptionPane.WARNING_MESSAGE);
                    Tools.clearText(this);
                    jCategory.setSelectedItem(null);
                    jsection.setSelectedItem(null);
                    update.setEnabled(false);
                    update.setVisible(true);
                    save.setVisible(false);
                    save.setEnabled(false);
                    delete.setVisible(false);
                    delete.setEnabled(false);
                    lestCategories();
                } else {
                    JOptionPane.showMessageDialog(this, "لم يتم التحديث", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void jTcatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTcatMouseClicked
        try {
            int row = jTcat.getSelectedRow();
            String num = jTcat.getValueAt(row, 9).toString();
            String bar = jTcat.getValueAt(row, 8).toString();
            String sec = jTcat.getValueAt(row, 7).toString();
            String cat = jTcat.getValueAt(row, 6).toString();
            String buy = jTcat.getValueAt(row, 5).toString();
            String sale = jTcat.getValueAt(row, 4).toString();
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            Date dateE = f.parse(jTcat.getValueAt(row, 3).toString());
            String mes = jTcat.getValueAt(row, 2).toString();
            String cnt = jTcat.getValueAt(row, 1).toString();
            String note = jTcat.getValueAt(row, 0).toString();

            id.setText(num);
            barcode.setText(bar);
            jCategory.setSelectedItem(cat);
            jsection.setSelectedItem(sec);
            priceBill.setText(sale);
            priceSale.setText(buy);
            jDateExpierd.setDate(dateE);
            jmeasuring.setSelectedItem(mes);
            count.setText(cnt);
            notes.setText(note);

            update.setEnabled(true);
            update.setVisible(true);
            delete.setVisible(true);
            delete.setEnabled(true);
            save.setVisible(false);
            save.setEnabled(false);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jTcatMouseClicked

    private void SearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyTyped
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ملاحظات");
        table.addColumn("العدد او الكمية");
        table.addColumn("وحدة القياس");
        table.addColumn("انتهاء الصلاحية");
        table.addColumn("سعر الشراء");
        table.addColumn("سعر البيع");
        table.addColumn("اسم الصنف");
        table.addColumn("القسم");
        table.addColumn("الباركود");
        table.addColumn("الرقم");

        try {
            Connection con = ConectionDB.setcon();
            String sqls = "select * from categories where Barcode like '%" + Search.getText() + "%' or Section like '%" + Search.getText()
                    + "%' or Category like '%" + Search.getText() + "%'";

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sqls);

            while (rs.next()) {
                table.addRow(new Object[]{
                    rs.getString(10),
                    rs.getString(9),
                    rs.getString(8),
                    rs.getString(7),
                    rs.getString(6),
                    rs.getString(5),
                    rs.getString(4),
                    rs.getString(3),
                    rs.getString(2),
                    rs.getString(1),});
                jTcat.setModel(table);

            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_SearchKeyTyped

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int d = JOptionPane.showConfirmDialog(this, "هل تريد حذف الصنف المحدد ؟");
        if (d == JOptionPane.YES_OPTION) {
            int row = jTcat.getSelectedRow();
            String num = jTcat.getValueAt(row, 9).toString();
            String strD = "DELETE FROM CATEGORIES WHERE NUMBER =" + num;
            boolean ifD = DB.GoDB.runNunQuery(strD);
            if (ifD) {
                JOptionPane.showMessageDialog(null, "تم حذف الصنف المحدد", "نجح", JOptionPane.WARNING_MESSAGE);
                lestCategories();
                delete.setEnabled(false);
                Tools.clearText(this);
                jCategory.setSelectedItem(null);
                jsection.setSelectedItem(null);
                update.setEnabled(false);
                update.setVisible(true);
                save.setVisible(false);
                save.setEnabled(false);
                delete.setVisible(false);
                delete.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "لم يتم حذف الصنف", "خطأ", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Search;
    private javax.swing.JLabel backgraund;
    private javax.swing.JTextField barcode;
    private javax.swing.JTextField count;
    private javax.swing.JButton delete;
    private javax.swing.JButton home;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    public static final javax.swing.JComboBox<String> jCategory = new javax.swing.JComboBox<>();
    private com.toedter.calendar.JDateChooser jDateExpierd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTcat;
    private javax.swing.JComboBox<String> jmeasuring;
    public static final javax.swing.JComboBox<String> jsection = new javax.swing.JComboBox<>();
    private javax.swing.JButton newCat;
    private javax.swing.JTextArea notes;
    private javax.swing.JTextField priceBill;
    private javax.swing.JTextField priceSale;
    private javax.swing.JButton save;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
