/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import DB.ConectionDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmed
 */
public class details extends javax.swing.JFrame {

    /**
     * Creates new form details
     */
    public details() {
        initComponents();
        jTdetails.getTableHeader().setReorderingAllowed(false);
        DB.GoDB.icon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane1.setOpaque(false);

        jTdetails.setBackground(new java.awt.Color(0, 153, 0));
        jTdetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTdetails.setForeground(new java.awt.Color(255, 255, 255));
        jTdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, "", "", null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "السعر", "العدد او الكمية", "القسم", "اسم الصنف", "رقم الفاتورة", "الرقم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTdetails.setGridColor(new java.awt.Color(51, 51, 0));
        jTdetails.setOpaque(false);
        jTdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTdetails);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 700, 290);

        setSize(new java.awt.Dimension(716, 327));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTdetailsMouseClicked
        
    }//GEN-LAST:event_jTdetailsMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int row = Accounts.jTSBill.getSelectedRow();
        String numBill = Accounts.jTSBill.getValueAt(row, 6).toString();

            DefaultTableModel table = new DefaultTableModel();
            table.addColumn("السعر");
            table.addColumn("العدد او الكمية");
            table.addColumn("القسم");
            table.addColumn("اسم الصنف");
            table.addColumn("رقم الفاتورة");
            table.addColumn("الرقم");

            try {
                Connection con = ConectionDB.setcon();
                String sqls = "SELECT * FROM BILLLINE WHERE NUMBERBILL=" + numBill;
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sqls);

                while (rs.next()) {
                    table.addRow(new Object[]{
                        rs.getString(11),
                        rs.getString(10),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(4),
                        rs.getString(3),});
                    details.jTdetails.setModel(table);
                }
            } catch (Exception ex) {
            }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    public static final javax.swing.JTable jTdetails = new javax.swing.JTable();
    // End of variables declaration//GEN-END:variables
}
