/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controls.Tools;
import Entity.Reports;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmed
 */
public class ReportsFrm extends javax.swing.JFrame {

    /**
     * Creates new form ReportsFrm
     */
    public ReportsFrm() {
        initComponents();
        day.setVisible(false);
        day.setEnabled(false);
        days.setVisible(false);
        days.setEnabled(false);
        printbtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        billbtn = new javax.swing.JButton();
        billlinebtn = new javax.swing.JButton();
        accbtn = new javax.swing.JButton();
        storedbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        printbtn = new javax.swing.JButton();
        panlSearch = new javax.swing.JPanel();
        daybtn = new javax.swing.JRadioButton();
        daysbtn = new javax.swing.JRadioButton();
        day = new javax.swing.JPanel();
        jDateOne = new com.toedter.calendar.JDateChooser();
        searchDaybtn = new javax.swing.JButton();
        days = new javax.swing.JPanel();
        searchDaysbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateFrom = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jDateTo = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 960, 260));

        billbtn.setBackground(new java.awt.Color(177, 1, 1));
        billbtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        billbtn.setForeground(new java.awt.Color(255, 255, 255));
        billbtn.setText("الفواتير");
        billbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        billbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billbtnActionPerformed(evt);
            }
        });
        getContentPane().add(billbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 40, 160, 60));

        billlinebtn.setBackground(new java.awt.Color(177, 1, 1));
        billlinebtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        billlinebtn.setForeground(new java.awt.Color(255, 255, 255));
        billlinebtn.setText("تفاصيل الفواتير");
        billlinebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        billlinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billlinebtnActionPerformed(evt);
            }
        });
        getContentPane().add(billlinebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 180, 160, 60));

        accbtn.setBackground(new java.awt.Color(177, 1, 1));
        accbtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        accbtn.setForeground(new java.awt.Color(255, 255, 255));
        accbtn.setText("إجمالي اليوم");
        accbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accbtnActionPerformed(evt);
            }
        });
        getContentPane().add(accbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 160, 60));

        storedbtn.setBackground(new java.awt.Color(177, 1, 1));
        storedbtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        storedbtn.setForeground(new java.awt.Color(255, 255, 255));
        storedbtn.setText("المخزن");
        storedbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        storedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storedbtnActionPerformed(evt);
            }
        });
        getContentPane().add(storedbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 160, 60));

        exitbtn.setBackground(new java.awt.Color(255, 153, 102));
        exitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitbtn.setText("خروج");
        exitbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 40));

        printbtn.setBackground(new java.awt.Color(0, 51, 51));
        printbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printbtn.setForeground(new java.awt.Color(255, 255, 255));
        printbtn.setText("طباعة التقرير");
        printbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        getContentPane().add(printbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 170, 40));

        panlSearch.setOpaque(false);
        panlSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daybtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        daybtn.setText("باليوم");
        daybtn.setOpaque(false);
        daybtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                daybtnItemStateChanged(evt);
            }
        });
        panlSearch.add(daybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        daysbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        daysbtn.setText("بالفترة");
        daysbtn.setOpaque(false);
        daysbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                daysbtnItemStateChanged(evt);
            }
        });
        panlSearch.add(daysbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        day.setOpaque(false);
        day.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateOne.setDateFormatString("yyyy-MM-dd");
        day.add(jDateOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 8, 250, 25));

        searchDaybtn.setBackground(new java.awt.Color(204, 204, 204));
        searchDaybtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchDaybtn.setText("بحث");
        searchDaybtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchDaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDaybtnActionPerformed(evt);
            }
        });
        day.add(searchDaybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        panlSearch.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 530, 40));

        days.setOpaque(false);
        days.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchDaysbtn.setBackground(new java.awt.Color(204, 204, 204));
        searchDaysbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchDaysbtn.setText("بحث");
        searchDaysbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchDaysbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDaysbtnActionPerformed(evt);
            }
        });
        days.add(searchDaysbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("من");
        days.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 30, 25));

        jDateFrom.setDateFormatString("yyyy-MM-dd");
        days.add(jDateFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 8, 140, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("إلى");
        days.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 10, 30, 25));

        jDateTo.setDateFormatString("yyyy-MM-dd");
        days.add(jDateTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 8, 140, 25));

        panlSearch.add(days, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 530, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search1.jpg"))); // NOI18N
        panlSearch.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        getContentPane().add(panlSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 750, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    String btnD = "";
    int btnR = 0;

    public void clickButton(JButton button1,
            JButton button2, JButton button3, JButton button4, int numberbool) {
        if (numberbool == 1) {
            button1.setBackground(new Color(33, 33, 33));
            button1.setForeground(Color.WHITE);
            button2.setBackground(new Color(177, 1, 1));
            button2.setForeground(Color.WHITE);
            button3.setBackground(new Color(177, 1, 1));
            button3.setForeground(Color.WHITE);
            button4.setBackground(new Color(177, 1, 1));
            button4.setForeground(Color.WHITE);
        } else {
            button1.setBackground(new Color(177, 1, 1));
            button1.setForeground(Color.WHITE);
            button2.setBackground(new Color(33, 33, 33));
            button2.setForeground(Color.WHITE);
            button3.setBackground(new Color(33, 33, 33));
            button3.setForeground(Color.WHITE);
            button4.setBackground(new Color(33, 33, 33));
            button4.setForeground(Color.WHITE);
        }
    }

    Reports rp = new Reports();
    HashMap pram = new HashMap();
    private void daybtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_daybtnItemStateChanged
        day.setVisible(true);
        day.setEnabled(true);
        days.setVisible(false);
        days.setEnabled(false);
        jDateOne.setCalendar(null);
        btnD = "day";
    }//GEN-LAST:event_daybtnItemStateChanged

    private void daysbtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_daysbtnItemStateChanged
        day.setVisible(false);
        day.setEnabled(false);
        days.setVisible(true);
        days.setEnabled(true);
        jDateFrom.setCalendar(null);
        jDateTo.setCalendar(null);
        btnD = "days";
    }//GEN-LAST:event_daysbtnItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        buttonGroup1.add(daybtn);
        buttonGroup1.add(daysbtn);
        DB.GoDB.icon(this);
        Tools.tableUI(jTable1);
    }//GEN-LAST:event_formWindowOpened

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void billbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billbtnActionPerformed
        btnR = 1;
        clickButton(billbtn, billlinebtn, accbtn, storedbtn, 1);

        panlSearch.setVisible(true);
        days.setVisible(false);
        day.setVisible(false);
        printbtn.setEnabled(false);
        jDateOne.setCalendar(null);
        jDateFrom.setCalendar(null);
        jDateTo.setCalendar(null);

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("الربح بعد الخصم");
        table.addColumn("الربح قبل الخصم");
        table.addColumn("إجمالي بعد الخصم");
        table.addColumn("الخصومات");
        table.addColumn("إجمالي البيع");
        table.addColumn("إجمالي الشراء");
        table.addColumn("الموظف");
        table.addColumn("الوقت");
        table.addColumn("التاريخ");
        table.addColumn("الفاتورة");
        jTable1.setModel(table);
    }//GEN-LAST:event_billbtnActionPerformed

    private void billlinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billlinebtnActionPerformed
        btnR = 2;
        clickButton(billlinebtn, billbtn, accbtn, storedbtn, 1);

        panlSearch.setVisible(true);
        days.setVisible(false);
        day.setVisible(false);
        printbtn.setEnabled(false);
        jDateOne.setCalendar(null);
        jDateFrom.setCalendar(null);
        jDateTo.setCalendar(null);

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("الربح");
        table.addColumn("إجمالي البيع");
        table.addColumn("إجمالي الشراء");
        table.addColumn("سعر البيع");
        table.addColumn("سعر الشراء");
        table.addColumn("القياس");
        table.addColumn("العدد");
        table.addColumn("المنتج");
        table.addColumn("الفاتورة");
        table.addColumn("التاريخ");
        jTable1.setModel(table);
    }//GEN-LAST:event_billlinebtnActionPerformed

    private void accbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accbtnActionPerformed
        btnR = 3;
        clickButton(accbtn, billlinebtn, billbtn, storedbtn, 1);

        panlSearch.setVisible(true);
        days.setVisible(false);
        day.setVisible(false);
        printbtn.setEnabled(false);
        jDateOne.setCalendar(null);
        jDateFrom.setCalendar(null);
        jDateTo.setCalendar(null);

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("الربح بعد الخصم");
        table.addColumn("الربح قبل الخصم");
        table.addColumn("إجمالي بعد الخصم");
        table.addColumn("الخصومات");
        table.addColumn("المصروفات");
        table.addColumn("إجمالي البيع");
        table.addColumn("إجمالي الشراء");
        table.addColumn("التاريخ");
        jTable1.setModel(table);
    }//GEN-LAST:event_accbtnActionPerformed

    private void storedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storedbtnActionPerformed
        btnR = 4;
        clickButton(storedbtn, billlinebtn, billbtn, accbtn, 1);

        panlSearch.setVisible(false);
        days.setVisible(false);
        day.setVisible(false);
        printbtn.setEnabled(true);

        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ملاحظات");
        table.addColumn("العدد");
        table.addColumn("وحدة القياس");
        table.addColumn("تاريخ الإنتهاء");
        table.addColumn("سعر البيع");
        table.addColumn("سعر الشراء");
        table.addColumn("المنتج");
        table.addColumn("القسم");
        table.addColumn("الباركود");
        table.addColumn("التسلسل");
        jTable1.setModel(table);
        rp.getAllStored(jTable1);
    }//GEN-LAST:event_storedbtnActionPerformed

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        if (btnR == 1) {
            System.out.println("R :" + btnR);
            if (btnD.equals("day") && jDateOne.getCalendar() != null) {

                String OneDate = dateFormat.format(jDateOne.getDate());
                pram.put("DateOnePram", OneDate);
                rp.setReport("billOneReport", pram);

            } else if (btnD.equals("days") && jDateFrom.getCalendar() != null && jDateTo.getCalendar() != null) {

                String DateFrom = dateFormat.format(jDateFrom.getDate());
                String DateTo = dateFormat.format(jDateTo.getDate());
                pram.put("DateFromPram", DateFrom);
                pram.put("DateToPram", DateTo);
                rp.setReport("billManyReport", pram);

            }
        } else if (btnR == 2) {
            if (btnD.equals("day") && jDateOne.getCalendar() != null) {

                String OneDate = dateFormat.format(jDateOne.getDate());
                pram.put("DateOnePram", OneDate);
                rp.setReport("billlineOneReport", pram);

            } else if (btnD.equals("days") && jDateFrom.getCalendar() != null && jDateTo.getCalendar() != null) {

                String DateFrom = dateFormat.format(jDateFrom.getDate());
                String DateTo = dateFormat.format(jDateTo.getDate());
                pram.put("DateFromPram", DateFrom);
                pram.put("DateToPram", DateTo);
                rp.setReport("billlineManyReport", pram);

            }

        } else if (btnR == 3) {
            if (btnD.equals("day") && jDateOne.getCalendar() != null) {

                String OneDate = dateFormat.format(jDateOne.getDate());
                pram.put("DateOnePram", OneDate);
                rp.setReport("accountsOneReport", pram);

            } else if (btnD.equals("days") && jDateFrom.getCalendar() != null && jDateTo.getCalendar() != null) {

                String DateFrom = dateFormat.format(jDateFrom.getDate());
                String DateTo = dateFormat.format(jDateTo.getDate());
                pram.put("DateFromPram", DateFrom);
                pram.put("DateToPram", DateTo);
                rp.setReport("accountsManyReport", pram);

            }
        } else if (btnR == 4) {

            rp.setReport("storedReport", null);
        }
    }//GEN-LAST:event_printbtnActionPerformed

    private void searchDaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDaybtnActionPerformed
        if (jDateOne.getCalendar() == null) {
            Tools.msgbox("ادخل التاريخ اولا !!");
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dateOne = dateFormat.format(jDateOne.getDate());

            if (btnR == 1) {
                rp.getAccByOneDate(dateOne, jTable1);
                printbtn.setEnabled(true);
            } else if (btnR == 2) {
                rp.getAllAccountsBillLineOne(dateOne, jTable1);
                printbtn.setEnabled(true);
            } else if (btnR == 3) {
                rp.getAllAccountsDayOne(dateOne, jTable1);
                printbtn.setEnabled(true);
            }

        }
    }//GEN-LAST:event_searchDaybtnActionPerformed

    private void searchDaysbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDaysbtnActionPerformed
        if (jDateFrom.getCalendar() == null || jDateTo.getCalendar() == null) {
            Tools.msgbox("ادخل التاريخ اولا !!");
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String datef = dateFormat.format(jDateFrom.getDate());
            String datet = dateFormat.format(jDateTo.getDate());

            if (btnR == 1) {
                rp.getAccByManyDate(datef, datet, jTable1);
                printbtn.setEnabled(true);
            } else if (btnR == 2) {
                rp.getAllAccountsBillLineMany(datef, datet, jTable1);
                printbtn.setEnabled(true);
            } else if (btnR == 3) {
                rp.getAllAccountsDayMany(datef, datet, jTable1);
                printbtn.setEnabled(true);
            }
        }
    }//GEN-LAST:event_searchDaysbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accbtn;
    private javax.swing.JButton billbtn;
    private javax.swing.JButton billlinebtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel day;
    private javax.swing.JRadioButton daybtn;
    private javax.swing.JPanel days;
    private javax.swing.JRadioButton daysbtn;
    private javax.swing.JButton exitbtn;
    private com.toedter.calendar.JDateChooser jDateFrom;
    private com.toedter.calendar.JDateChooser jDateOne;
    private com.toedter.calendar.JDateChooser jDateTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panlSearch;
    private javax.swing.JButton printbtn;
    private javax.swing.JButton searchDaybtn;
    private javax.swing.JButton searchDaysbtn;
    private javax.swing.JButton storedbtn;
    // End of variables declaration//GEN-END:variables
}
