/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controls.Tools;
import DB.ConectionDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmed
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
        categoryDiv.setVisible(false);
        categoryDiv.setEnabled(false);
        sectionDiv.setVisible(false);
        sectionDiv.setEnabled(false);
        expierdDiv.setVisible(false);
        expierdDiv.setEnabled(false);
        jTStore.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchGroup = new javax.swing.ButtonGroup();
        rbtncat = new javax.swing.JRadioButton();
        rbtnsec = new javax.swing.JRadioButton();
        rbtnexpi = new javax.swing.JRadioButton();
        serchBy = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTStore = new javax.swing.JTable();
        Exit = new javax.swing.JButton();
        expierdDiv = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        goDat = new javax.swing.JButton();
        countDat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDateExpierd = new com.toedter.calendar.JDateChooser();
        sectionDiv = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sect = new javax.swing.JTextField();
        categ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jsection = new javax.swing.JComboBox<>();
        categoryDiv = new javax.swing.JPanel();
        searchCat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        go = new javax.swing.JButton();
        countCat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        rbtncat.setBackground(new java.awt.Color(255, 255, 255));
        rbtncat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtncat.setForeground(new java.awt.Color(255, 153, 102));
        rbtncat.setText(" الصنف");
        rbtncat.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rbtncat.setOpaque(false);
        rbtncat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtncatItemStateChanged(evt);
            }
        });
        getContentPane().add(rbtncat);
        rbtncat.setBounds(850, 60, 90, 19);

        rbtnsec.setBackground(new java.awt.Color(255, 255, 255));
        rbtnsec.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtnsec.setForeground(new java.awt.Color(255, 153, 102));
        rbtnsec.setText(" القسم");
        rbtnsec.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rbtnsec.setOpaque(false);
        rbtnsec.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnsecItemStateChanged(evt);
            }
        });
        getContentPane().add(rbtnsec);
        rbtnsec.setBounds(760, 60, 90, 19);

        rbtnexpi.setBackground(new java.awt.Color(255, 255, 255));
        rbtnexpi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rbtnexpi.setForeground(new java.awt.Color(255, 153, 102));
        rbtnexpi.setText("تاريخ الانتهاء");
        rbtnexpi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        rbtnexpi.setOpaque(false);
        rbtnexpi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnexpiItemStateChanged(evt);
            }
        });
        getContentPane().add(rbtnexpi);
        rbtnexpi.setBounds(640, 60, 110, 19);

        serchBy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serchBy.setForeground(new java.awt.Color(255, 153, 102));
        serchBy.setText("بحث بـ :");
        getContentPane().add(serchBy);
        serchBy.setBounds(900, 35, 52, 17);

        jTStore.setBackground(new java.awt.Color(255, 153, 102));
        jTStore.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTStore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTStore.setForeground(new java.awt.Color(14, 97, 10));
        jTStore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, "", ""},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ملاحظات", "العدد او الكمية", "وحدة القياس", "انتهاء الصلاحية", "سعر البيع", "سعر الشراء", "اسم الصنف", "القسم", "الباركود", "الرقم"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTStore.setOpaque(false);
        jScrollPane1.setViewportView(jTStore);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 299, 980, 290);

        Exit.setBackground(new java.awt.Color(255, 153, 102));
        Exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(14, 97, 10));
        Exit.setText("خروج");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(30, 40, 140, 50);

        expierdDiv.setOpaque(false);
        expierdDiv.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("بحث :");
        expierdDiv.add(jLabel12);
        jLabel12.setBounds(700, 15, 50, 17);

        goDat.setBackground(new java.awt.Color(255, 153, 102));
        goDat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        goDat.setForeground(new java.awt.Color(14, 97, 10));
        goDat.setText("بحث");
        goDat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goDatActionPerformed(evt);
            }
        });
        expierdDiv.add(goDat);
        goDat.setBounds(10, 10, 60, 30);

        countDat.setEditable(false);
        countDat.setBackground(new java.awt.Color(204, 204, 204));
        countDat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        countDat.setForeground(new java.awt.Color(14, 97, 10));
        countDat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expierdDiv.add(countDat);
        countDat.setBounds(320, 80, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("العدد");
        expierdDiv.add(jLabel8);
        jLabel8.setBounds(320, 50, 130, 22);

        jDateExpierd.setDateFormatString("yyyy-MM-dd");
        expierdDiv.add(jDateExpierd);
        jDateExpierd.setBounds(81, 10, 610, 30);

        getContentPane().add(expierdDiv);
        expierdDiv.setBounds(200, 125, 770, 130);

        sectionDiv.setOpaque(false);
        sectionDiv.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("بحث :");
        sectionDiv.add(jLabel11);
        jLabel11.setBounds(700, 15, 50, 17);

        search.setBackground(new java.awt.Color(255, 153, 102));
        search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        search.setForeground(new java.awt.Color(14, 97, 10));
        search.setText("بحث");
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        sectionDiv.add(search);
        search.setBounds(10, 10, 60, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("القسم");
        sectionDiv.add(jLabel6);
        jLabel6.setBounds(460, 50, 60, 22);

        sect.setEditable(false);
        sect.setBackground(new java.awt.Color(204, 204, 204));
        sect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sect.setForeground(new java.awt.Color(14, 97, 10));
        sect.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sectionDiv.add(sect);
        sect.setBounds(430, 80, 110, 30);

        categ.setEditable(false);
        categ.setBackground(new java.awt.Color(204, 204, 204));
        categ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        categ.setForeground(new java.awt.Color(14, 97, 10));
        categ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sectionDiv.add(categ);
        categ.setBounds(210, 80, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("عدد الاصناف");
        sectionDiv.add(jLabel7);
        jLabel7.setBounds(210, 50, 110, 22);

        jsection.setBackground(new java.awt.Color(204, 204, 204));
        jsection.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jsection.setForeground(new java.awt.Color(14, 97, 10));
        jsection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jsectionItemStateChanged(evt);
            }
        });
        sectionDiv.add(jsection);
        jsection.setBounds(76, 10, 620, 30);

        getContentPane().add(sectionDiv);
        sectionDiv.setBounds(200, 125, 770, 130);

        categoryDiv.setOpaque(false);
        categoryDiv.setLayout(null);

        searchCat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchCat.setForeground(new java.awt.Color(14, 97, 10));
        searchCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchCatKeyPressed(evt);
            }
        });
        categoryDiv.add(searchCat);
        searchCat.setBounds(80, 10, 613, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("بحث :");
        categoryDiv.add(jLabel10);
        jLabel10.setBounds(700, 15, 50, 17);

        go.setBackground(new java.awt.Color(255, 153, 102));
        go.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        go.setForeground(new java.awt.Color(14, 97, 10));
        go.setText("بحث");
        go.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        categoryDiv.add(go);
        go.setBounds(10, 10, 60, 30);

        countCat.setEditable(false);
        countCat.setBackground(new java.awt.Color(204, 204, 204));
        countCat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        countCat.setForeground(new java.awt.Color(14, 97, 10));
        countCat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        categoryDiv.add(countCat);
        countCat.setBounds(320, 80, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("العدد");
        categoryDiv.add(jLabel3);
        jLabel3.setBounds(320, 50, 130, 22);

        getContentPane().add(categoryDiv);
        categoryDiv.setBounds(200, 125, 770, 130);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/e1557147841512.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1002, 602);

        setSize(new java.awt.Dimension(1000, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void lestCategories() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ملاحظات");
        table.addColumn("العدد او الكمية");
        table.addColumn("وحدة القياس");
        table.addColumn("انتهاء الصلاحية");
        table.addColumn("سعر الشراء");
        table.addColumn("سعر البيع");
        table.addColumn("اسم الصنف");
        table.addColumn("القسم");
        table.addColumn("الباركود");
        table.addColumn("الرقم");

        try {
            Connection con = ConectionDB.setcon();
            String sqls = "select * from categories";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sqls);

            while (rs.next()) {
                table.addRow(new Object[]{
                    rs.getString(10),
                    rs.getString(9),
                    rs.getString(8),
                    rs.getString(7),
                    rs.getString(6),
                    rs.getString(5),
                    rs.getString(4),
                    rs.getString(3),
                    rs.getString(2),
                    rs.getString(1),});
                jTStore.setModel(table);

            }
        } catch (Exception ex) {

        }
    }

    public void lestCatSearchSec() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ملاحظات");
        table.addColumn("العدد او الكمية");
        table.addColumn("وحدة القياس");
        table.addColumn("انتهاء الصلاحية");
        table.addColumn("سعر الشراء");
        table.addColumn("سعر البيع");
        table.addColumn("اسم الصنف");
        table.addColumn("القسم");
        table.addColumn("الباركود");
        table.addColumn("الرقم");

        try {
            Connection con = ConectionDB.setcon();
            String sqls = "select * from categories where section like '%"+jsection.getSelectedItem()+"%'";            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sqls);

            while (rs.next()) {
                table.addRow(new Object[]{
                    rs.getString(10),
                    rs.getString(9),
                    rs.getString(8),
                    rs.getString(7),
                    rs.getString(6),
                    rs.getString(5),
                    rs.getString(4),
                    rs.getString(3),
                    rs.getString(2),
                    rs.getString(1),});
                jTStore.setModel(table);
                sect.setText(rs.getString(3));

            }
        } catch (Exception ex) {

        }
    }

    public void lestCatSearch() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ملاحظات");
        table.addColumn("العدد او الكمية");
        table.addColumn("وحدة القياس");
        table.addColumn("انتهاء الصلاحية");
        table.addColumn("سعر الشراء");
        table.addColumn("سعر البيع");
        table.addColumn("اسم الصنف");
        table.addColumn("القسم");
        table.addColumn("الباركود");
        table.addColumn("الرقم");

        try {
            Connection con = ConectionDB.setcon();
            String sqls = "select * from categories where category like '%"+searchCat.getText()+"%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sqls);

            while (rs.next()) {
                table.addRow(new Object[]{
                    rs.getString(10),
                    rs.getString(9),
                    rs.getString(8),
                    rs.getString(7),
                    rs.getString(6),
                    rs.getString(5),
                    rs.getString(4),
                    rs.getString(3),
                    rs.getString(2),
                    rs.getString(1),});
                jTStore.setModel(table);

            }
        } catch (Exception ex) {

        }
    }

    public void lestCatSearchExpierd() {
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ملاحظات");
        table.addColumn("العدد او الكمية");
        table.addColumn("وحدة القياس");
        table.addColumn("انتهاء الصلاحية");
        table.addColumn("سعر الشراء");
        table.addColumn("سعر البيع");
        table.addColumn("اسم الصنف");
        table.addColumn("القسم");
        table.addColumn("الباركود");
        table.addColumn("الرقم");

        try {
            Connection con = ConectionDB.setcon();
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String dateE = f.format(jDateExpierd.getDate());
            String sqls = "select * from categories where expierd_date like '%"+dateE+"%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sqls);

            while (rs.next()) {
                table.addRow(new Object[]{
                    rs.getString(10),
                    rs.getString(9),
                    rs.getString(8),
                    rs.getString(7),
                    rs.getString(6),
                    rs.getString(5),
                    rs.getString(4),
                    rs.getString(3),
                    rs.getString(2),
                    rs.getString(1),});
                jTStore.setModel(table);

            }
        } catch (Exception ex) {

        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DB.GoDB.icon(this);
        searchGroup.add(rbtncat);
        searchGroup.add(rbtnsec);
        searchGroup.add(rbtnexpi);
        lestCategories();
    }//GEN-LAST:event_formWindowOpened

    private void rbtncatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtncatItemStateChanged
        categoryDiv.setVisible(true);
        categoryDiv.setEnabled(true);
        sectionDiv.setVisible(false);
        sectionDiv.setEnabled(false);
        expierdDiv.setVisible(false);
        expierdDiv.setEnabled(false);
        Tools.clearText(this);
        jsection.setSelectedItem(null);
        lestCategories();
    }//GEN-LAST:event_rbtncatItemStateChanged

    private void rbtnsecItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnsecItemStateChanged
        categoryDiv.setVisible(false);
        categoryDiv.setEnabled(false);
        sectionDiv.setVisible(true);
        sectionDiv.setEnabled(true);
        expierdDiv.setVisible(false);
        expierdDiv.setEnabled(false);
        lestCategories();
        DB.GoDB.fillCompo("sections", "section", jsection);
        jsection.setSelectedItem(null);
        Tools.clearText(this);
    }//GEN-LAST:event_rbtnsecItemStateChanged

    private void rbtnexpiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnexpiItemStateChanged
        categoryDiv.setVisible(false);
        categoryDiv.setEnabled(false);
        sectionDiv.setVisible(false);
        sectionDiv.setEnabled(false);
        expierdDiv.setVisible(true);
        expierdDiv.setEnabled(true);
        Tools.clearText(this);
        jsection.setSelectedItem(null);
        lestCategories();
    }//GEN-LAST:event_rbtnexpiItemStateChanged

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void jsectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jsectionItemStateChanged
        lestCatSearchSec();
        try{
            String ca = "select count(section) as num from categories where section='"+jsection.getSelectedItem()+"'";
            Connection con = ConectionDB.setcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(ca);
            String num = "";
            while (rs.next()) {
                num = st.getResultSet().getString("num");
            }
            con.close();
            if (num == null || "".equals(num)) {
                categ.setText("0");
            } else {
                categ.setText(num);
            }
            
        }catch(Exception ex){
        
        }
    }//GEN-LAST:event_jsectionItemStateChanged

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        lestCatSearchSec();
        try{
            String ca = "select count(section) as num from categories where section='"+jsection.getSelectedItem()+"'";
            Connection con = ConectionDB.setcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(ca);
            String num = "";
            while (rs.next()) {
                num = st.getResultSet().getString("num");
            }
            con.close();
            if (num == null || "".equals(num)) {
                categ.setText("0");
            } else {
                categ.setText(num);
            }
            
        }catch(Exception ex){
        
        }
    }//GEN-LAST:event_searchActionPerformed

    private void goDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goDatActionPerformed
        lestCatSearchExpierd();
        try{
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            String dateE = f.format(jDateExpierd.getDate());
            String ca = "select count(expierd_date) as num from categories where expierd_date like '%"+dateE+"%'";
            Connection con = ConectionDB.setcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(ca);
            String num = "";
            while (rs.next()) {
                num = st.getResultSet().getString("num");
            }
            con.close();
            if (num == null || "".equals(num)) {
                countDat.setText("0");
            } else {
                countDat.setText(num);
            }
            
        }catch(Exception ex){
        
        }
    }//GEN-LAST:event_goDatActionPerformed

    private void searchCatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchCatKeyPressed
        lestCatSearch();
        try{
            String ca = "select count(category) as num from categories where category like '%"+searchCat.getText()+"%'";
            Connection con = ConectionDB.setcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(ca);
            String num = "";
            while (rs.next()) {
                num = st.getResultSet().getString("num");
            }
            con.close();
            if (num == null || "".equals(num)) {
                countCat.setText("0");
            } else {
                countCat.setText(num);
            }
            
        }catch(Exception ex){
        
        }
    }//GEN-LAST:event_searchCatKeyPressed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        lestCatSearch();
        try{
            String ca = "select count(category) as num from categories where category like '%"+searchCat.getText()+"%'";
            Connection con = ConectionDB.setcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(ca);
            String num = "";
            while (rs.next()) {
                num = st.getResultSet().getString("num");
            }
            con.close();
            if (num == null || "".equals(num)) {
                countCat.setText("0");
            } else {
                countCat.setText(num);
            }
        }catch(Exception ex){
        
        }
    }//GEN-LAST:event_goActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JTextField categ;
    private javax.swing.JPanel categoryDiv;
    private javax.swing.JTextField countCat;
    private javax.swing.JTextField countDat;
    private javax.swing.JPanel expierdDiv;
    private javax.swing.JButton go;
    private javax.swing.JButton goDat;
    private com.toedter.calendar.JDateChooser jDateExpierd;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTStore;
    private javax.swing.JComboBox<String> jsection;
    private javax.swing.JRadioButton rbtncat;
    private javax.swing.JRadioButton rbtnexpi;
    private javax.swing.JRadioButton rbtnsec;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchCat;
    private javax.swing.ButtonGroup searchGroup;
    private javax.swing.JTextField sect;
    private javax.swing.JPanel sectionDiv;
    private javax.swing.JLabel serchBy;
    // End of variables declaration//GEN-END:variables
}
